version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: front-end/Dockerfile
      cache_from:
        - trading-bot-frontend:latest
    image: trading-bot-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    command: node server.js
    # Si vous avez besoin de volumes pour le développement
    #volumes:
    #  - ./front-end:/app
    #  - /app/node_modules
    #  - /app/.next