services:
  frontend:
    build:
      context: ..
      dockerfile: front-end/Dockerfile
      cache_from:
        - trading-bot-frontend:latest
    image: trading-bot-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped